INSERT INTO filme (nome, ano, descricao, img) VALUES
('Inception', 2010, 'Um ladrão que compartilha sonhos.', 'https://image.tmdb.org/t/p/w500/qmDpIHrmpJINaRKAfWQfftjCdyi.jpg'),
('The Matrix', 1999, 'Um hacker descobre a realidade.', 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg'),
('Interstellar', 2014, 'Exploradores viajam por um buraco de minhoca.', 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg'),
('The Dark Knight', 2008, 'Batman contra o Coringa.', 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg'),
('Forrest Gump', 1994, 'Um homem com QI baixo alcança grandes feitos.', 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg'),
('The Shawshank Redemption', 1994, 'Dois homens presos encontram redenção.', 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg'),
('Pulp Fiction', 1994, 'Histórias entrelaçadas de violência e redenção.', 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg'),
('Fight Club', 1999, 'Um clube de luta clandestino.', 'https://image.tmdb.org/t/p/w500/bptfVGEQuv6vDTIMVCHjJ9Dz8PX.jpg'),
('The Godfather', 1972, 'Um patriarca de uma dinastia criminosa transfere o controle.', 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg'),
('The Lord of the Rings', 2001, 'Uma jornada para destruir um anel poderoso.', 'https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg'),
('Star Wars', 1977, 'Um jovem se junta a uma luta galáctica.', 'https://image.tmdb.org/t/p/w500/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg'),
('Jurassic Park', 1993, 'Dinossauros soltos em um parque temático.', 'https://image.tmdb.org/t/p/w500/c414cDeQ9b6qLPLeKmiJuLDUREJ.jpg'),
('The Lion King', 1994, 'Um príncipe leão enfrenta seu tio.', 'https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg'),
('Back to the Future', 1985, 'Um adolescente viaja no tempo.', 'https://image.tmdb.org/t/p/w500/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg'),
('Gladiator', 2000, 'Um general busca vingança.', 'https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg'),
('Titanic', 1997, 'Uma história de amor no navio condenado.', 'https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg'),
('Avatar', 2009, 'Um fuzileiro em uma missão em Pandora.', 'https://image.tmdb.org/t/p/w500/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg'),
('The Avengers', 2012, 'Heróis se unem para salvar o mundo.', 'https://image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg'),
('Harry Potter', 2001, 'Um garoto descobre que é um bruxo.', 'https://image.tmdb.org/t/p/w500/foT7ZTJlUQgmXGKNkt93SzwI0K.jpg'),
('Toy Story', 1995, 'Brinquedos ganham vida.', 'https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg');
