INSERT INTO filme (nome, ano, descricao) VALUES
('Inception', 2010, 'Um ladrão que compartilha sonhos.'),
('The Matrix', 1999, 'Um hacker descobre a realidade.'),
('Interstellar', 2014, 'Exploradores viajam por um buraco de minhoca.'),
('The Dark Knight', 2008, 'Batman contra o Coringa.'),
('Forrest Gump', 1994, 'Um homem com QI baixo alcança grandes feitos.'),
('The Shawshank Redemption', 1994, 'Dois homens presos encontram redenção.'),
('Pulp Fiction', 1994, 'Histórias entrelaçadas de violência e redenção.'),
('Fight Club', 1999, 'Um clube de luta clandestino.'),
('The Godfather', 1972, 'Um patriarca de uma dinastia criminosa transfere o controle.'),
('The Lord of the Rings', 2001, 'Uma jornada para destruir um anel poderoso.'),
('Star Wars', 1977, 'Um jovem se junta a uma luta galáctica.'),
('Jurassic Park', 1993, 'Dinossauros soltos em um parque temático.'),
('The Lion King', 1994, 'Um príncipe leão enfrenta seu tio.'),
('Back to the Future', 1985, 'Um adolescente viaja no tempo.'),
('Gladiator', 2000, 'Um general busca vingança.'),
('Titanic', 1997, 'Uma história de amor no navio condenado.'),
('Avatar', 2009, 'Um fuzileiro em uma missão em Pandora.'),
('The Avengers', 2012, 'Heróis se unem para salvar o mundo.'),
('Harry Potter', 2001, 'Um garoto descobre que é um bruxo.'),
('Toy Story', 1995, 'Brinquedos ganham vida.');