
CREATE DATABASE  filmesdb;

USE filmesdb;

CREATE TABLE IF NOT EXISTS filme(
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    nome VARCHAR(100) NOT NULL,
    ano INT NOT NULL,
    descricao TEXT NOT NULL,
    img VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);